<template>
   <div><div><div class="bg-white py-20"><div><div nestedcomponents="" class="max-w-[85rem] mx-auto px-4 sm:px-6 lg:px-8"><div class="grid lg:grid-cols-2 gap-4 md:gap-8 xl:gap-20 md:items-center"><div><h1 class="mb-4 tracking-tight leading-none hero-line-height font-extrabold text-4xl lg:text-6xl text-primary">
        Contact Us
      </h1> <p class="mt-3 lg:text-2xl text-normalfont-semibold text-primary-2">
        Optimize Your Success with Our Global Delivery Model!
      </p> <!----></div> <div class="relative ml-4"><img src="https://preview-assets-us-01.kc-usercontent.com:443/d21c04b3-d8e3-0069-0344-815518ff2064/d79d3bd8-71af-4a33-975c-98004d1c30fc/image%2026.svg" alt="Image Description" class="w-full rounded-md"></div></div></div></div></div></div><div><div class="bg-white"><div><div nestedcomponents="" class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto"><div class="grid lg:grid-cols-2 gap-4"><div class="pr-10 text-2xl"><p>Ready to redefine your digital identity with the latest in Jamstack technology?</p>
<p>At Nathan Ark, we bring your vision to life with seamless transitions, performance excellence, and cutting-edge security. Reach out&nbsp;today and transform your online presence into a scalable reality.</p></div> <div><form action="https://forms.zohopublic.in/machintelsystemspvtltd/form/NathanArkContactForm/formperma/e9kIxZijZzMZ7PNXuL-CJsITG98wxLbUwVqNePZBUvE/htmlRecords/submit" name="form" id="form" method="POST" accept-charset="UTF-8" enctype="multipart/form-data"><input type="hidden" name="zf_referrer_name"> <input type="hidden" name="zf_redirect_url"> <input type="hidden" name="zc_gad"> <div class="grid gap-4 lg:gap-6"><div class="grid grid-cols-1 sm:grid-cols-2 gap-4 lg:gap-6"><div><input placeholder="First Name" name="Name_First" fieldtype="7" class="py-3 px-4 block w-full border border-colors-primary-900 rounded-md text-sm text-colors-font"></div> <div><input placeholder="Last Name" name="Name_Last" fieldtype="7" class="py-3 px-4 block w-full border border-colors-primary-900 rounded-md text-sm text-colors-font"></div></div> <div><input type="email" placeholder="Email" name="Email" fieldtype="9" class="py-3 px-4 block w-full border border-colors-primary-900 rounded-md text-sm text-colors-font"></div> <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 lg:gap-6"><div><input placeholder="Company" name="SingleLine" fieldtype="1" class="py-3 px-4 block w-full border border-colors-primary-900 rounded-md text-sm text-colors-font"></div> <div><input placeholder="Phone" compname="PhoneNumber" name="PhoneNumber_countrycode" phoneformat="1" iscountrycodeenabled="false" class="py-3 px-4 block w-full border border-colors-primary-900 rounded-md text-sm text-colors-font"></div></div> <div><textarea name="MultiLine" maxlength="65535" placeholder="Message (optional)" class="py-3 px-4 block w-full border border-colors-primary-900 rounded-md text-sm text-colors-font"></textarea></div></div> <div class="mt-3 flex"><div><label for="remember-me" class="text-xs">By submitting this form I have read and acknowledged the <a href="https://machintel.com/privacy-policy" target="_blank" class="text-blue-600 decoration-2 underline font-medium">Privacy policy</a></label></div></div> <div class="mt-6 grid"><button type="submit" class="btn btn-primary">Submit</button></div></form></div></div></div></div></div></div></div>
          </template>
          
         <script>
         export default {
         name: 'contact-us'
          }
         </script>
         